### PR TITLE
Group models by obs_id for steps that use grouping

### PR DESCRIPTION
**Pull request by braingram**
Group by `meta.observation.obs_id`.

Fixes: https://github.com/spacetelescope/romancal/issues/1259

Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/11281421723
show 5 expected failures like the following:
```
   {'values_changed': {"root['roman']['meta']['group_id']": {'new_value': '0000201001001001001011010001',
                                                            'old_value': 'roman0000211_1101_1'}}}
```

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Comment by schlafly** [comment]
Thanks, this looks good.  

A separate issue, but I hadn't appreciated that we were storing group_id in the files.  I guess that's okay?  It's not in our schema, so it's an optional added thing.  Apparently tweakreg adds it, even for grism data where it's not doing anything and the step gets skipped.

This test seems to imply some special structure is expected in group_id, but I think the test itself is the only thing that assumes that structure so it's probably fine.
https://github.com/spacetelescope/romancal/blob/1945dad5eb600fe82acb865baf3f1d66da12dd7f/romancal/tweakreg/tests/test_tweakreg.py#L912-L927
Anyway, this change looks good and I'll spin some group_id investigation into a separate issue.  Can I ask you to handle the okifying?  Thanks!

**Review by schlafly — APPROVED** [review]

**Comment by schlafly** [comment]
FWIW, https://github.com/spacetelescope/romancal/issues/1450 .

**Comment by braingram** [comment]
@schlafly I rebased this and resolved the conflict (2 lines in a unit test following https://github.com/spacetelescope/romancal/pull/1445).

Any objection if I merge this?

**Comment by schlafly** [comment]
Go ahead.  Please okify afterward, thanks!  We've had a lot of other regtest-changing updates in the meantime, so it will require a fresh regtest to okify.

**Comment by braingram** [comment]
Regression tests for okifying started here: https://github.com/spacetelescope/RegressionTests/actions/runs/11487718465

I'll okify these when they finish.

**Comment by braingram** [comment]
Results okified, this should be a clean run: https://github.com/spacetelescope/RegressionTests/actions/runs/11488484303

**Pull request merged**
