### PR TITLE
vendorize and fix crds workflow

### PR DESCRIPTION
**Pull request by braingram**
Similar to https://github.com/spacetelescope/jwst/pull/8869

It looks like the roman crds server was just updated to now require a second argument for the curl command leading to failures in the CI on main:
https://github.com/spacetelescope/romancal/actions/runs/11443462254/job/31836161436

This vendorizes the crds contexts workflow and fixes it for the recent change to the roman crds server.

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Comment by braingram** [comment]
@schlafly this was the crds change I mentioned last week. It looks like it was deployed. This PR should fix the currently failing romancal CI.e

**Comment by braingram** [comment]
Closing and reopening to try to retrigger webbpsf data file download (since that is now failing possibly due to a cache key change with the crds update).

**Review by schlafly — APPROVED** [review]
Thanks Brett.  This looks good to me.  This is also the approach you are taking for Webb?

**Comment by braingram** [comment]
> Thanks Brett. This looks good to me. This is also the approach you are taking for Webb?

Thanks! Yeah https://github.com/spacetelescope/jwst/pull/8869 was merged (and gwcs went the same route: https://github.com/spacetelescope/gwcs/pull/518). Eventually it might be easier to consolidate this again but likely using the `crds` client directly rather than the `curl` commands as is currently done in the workflow. This PR is more a stop-gap until that work can be considered, prioritized and implemented.

**Comment by braingram** [comment]
I should have noted that as this doesn't touch any code or infrastructure related to the regression tests no regression tests were run.

**Pull request merged**
