### PR TITLE
move pytest markers to pyproject.toml

### PR DESCRIPTION
**Pull request by braingram**
remove pytest.ini

The existence of pytest.ini (introduced in https://github.com/spacetelescope/romancal/pull/411) prevented pytest from
reading options from pyproject.toml that for one
example disabled doctests

~~I'm expecting this will fail ci as at least one doctest contains a use of jwst:~~ Edited: fixed this reference
https://github.com/spacetelescope/romancal/blob/393d60f4702489d9e1d2f8b1fa7054e678b619b2/romancal/associations/registry.py#L63

which appears as a failure in the stpipe downstream ci testing of romancal:
https://github.com/spacetelescope/stpipe/actions/runs/4161774078/jobs/7200153620#step:8:39

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by braingram** [comment]
@ddavis-stsci pinging you as this pertains to the markers in pytest.ini. My apologies for turning on what appear to be broken tests :) Please let me know if I can help.

**Comment by braingram** [comment]
I did not find the data file used in the doctests in docs/roman/datamodels/datamodels_asdf
https://github.com/spacetelescope/romancal/blob/393d60f4702489d9e1d2f8b1fa7054e678b619b2/docs/roman/datamodels/datamodels_asdf.rst?plain=1#L148
so I added a doctest skip to each line. This might be better handled as a python code block if the intention is to not have these as doctests.

**Comment by ddavis-stsci** [comment]
> I did not find the data file used in the doctests in docs/roman/datamodels/datamodels_asdf
> 
> https://github.com/spacetelescope/romancal/blob/393d60f4702489d9e1d2f8b1fa7054e678b619b2/docs/roman/datamodels/datamodels_asdf.rst?plain=1#L148
> 
> so I added a doctest skip to each line. This might be better handled as a python code block if the intention is to not have these as doctests.

I'm curious about what kind of code block, right now it is in 
```
.. code:: python

    >>> from roman_datamodels import datamodels as rdm
    >>> d_uncal = rdm.open('r0000101001001001001_01101_0001_WFI01_uncal.asdf')
    >>> d_uncal.info()
```
Is there one that pyproject prefers?

**Review by ddavis-stsci — APPROVED** [review]
Looks good. I'll write a ticket to update the code blocks so we don't have to use the skips.

**Comment by braingram** [comment]
> Is there one that pyproject prefers?

I believe the issue is that the `>>>` makes pytest see it as a doctest (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#doctest-blocks) and try to execute the contained test as code to check that the output matches the output in the text.

Unfortunately the formatting is a bit different if the `>>>` is removed or replaced with `>>` as sphinx then complains `WARNING: Could not lex literal_block as "python". Highlighting skipped.`. Someone with more experience with sphinx may know how to coax it into produced highlighted non-doctest code blocks without the skips but I don't immediately see a solution.

**Pull request merged**
