### PR TITLE
RCAL-234 Fix Jump Unit Tests

### LINKED ISSUE #332: Fix Jump Unit Tests
_Issue [RCAL-234](https://jira.stsci.edu/browse/RCAL-234) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Fix jump test failures due to missing exposure metadata.

### PR DESCRIPTION
**Pull request by PaulHuwe**
Closes #332 

Resolves RCAL-234

**Description**

This PR updates temp readnoise file in jump tests to include required exposure keywords.

Checklist
- [x ] Tests

- [ ] Documentation

- [x ] Change log

- [x ] Milestone

- [x ] Label(s)

### CODE REVIEW

**Review by dmggh — APPROVED** [review]

**Comment by ddavis-stsci** [comment]
It looks like you are getting the same errors Dave G is seeing with an extra romancal in the path, 'PosixPath('/home/runner/work/romancal/romancal/romancal/' and conftest.py is at 
./romancal/romancal/conftest.py

**Comment by PaulHuwe** [comment]
Do we have a solution for that?

**Comment by dmggh** [comment]
No solution yet, Nadia has been looking into it.

**Comment by nden** [comment]
@PaulHuwe Please rebase on main to pick up tox changes.

**Comment by PaulHuwe** [comment]
Rebased.

**Comment by nden** [comment]
@PaulHuwe I think I fixed the last problem with the tox file. Please rebase again to see if everything passes now.

**Comment by PaulHuwe** [comment]
Rebased

**Review by ddavis-stsci — APPROVED** [review]
Yeah!

**Comment by PaulHuwe** [comment]
Yay! Go @nden !

**Pull request merged**
