### PR TITLE
update pull request checklist

### PR DESCRIPTION
**Pull request by zacharyburnett**
analogous to https://github.com/spacetelescope/jwst/pull/8670

# old checklist
---------------

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [N/A] ~updated relevant tests~
- [x] updated relevant documentation
- [x] updated relevant milestone(s)
- [x] added relevant label(s)
- [N/A] ~ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)~

# new checklist
---------------

## Tasks
- [x] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Comment by zacharyburnett** [comment]
> I think adding the build milestone is good. Otherwise my impression is that most of this is too "in the weeds" for a checklist. I'd add most of this to the "Tickets & PR" section of https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=SCSB&title=Roman+Calibration+Pipeline That page is more easily updated and flexible. Having the checklist be more generic also solves the problem of trying to keep both in sync.

That is good to have it on Innerspace; however, I think it is more important to have the checklist here as well, both to have the checklist be immediately visible (and less easily forgettable) and also have it accessible to outside contributors who can't see the Innerspace page. If I had a choice between keeping the checklist here or on Innerspace, I personally would choose here for that reason; however, I will yield to your suggestion if you think that is better

**Comment by ddavis-stsci** [comment]
If we want the instructions available to outside contributors I'd 
suggest that it be added to the github wiki page.

**Review by schlafly — APPROVED** [review]
Approving since this has also gone in on the Webb side.

**Comment by zacharyburnett** [comment]
also added to the wiki page at https://github.com/spacetelescope/romancal/wiki/Pull-Request-Checklist

**Pull request merged**
