### PR TITLE
Use same changelog workflow as the rest of the roman repositories

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This PR updates the changelog CI to use the same changelog workflow used by `rad` and `roman_datamodels`. This workflow draws from an independent centralized workflow that has several additional features (including milestone verification if we wish to turn that on).

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
The independent workflow is managed by @pllim.

**Comment by pllim** [comment]
FWIW Brigitta asked if I am interested to upstream this to Scientific Python but I was hesitant because I am scared it is going to get refactored and break stuff. But if STScI is not comfortable with this workflow in my own account, I can revisit that idea with Brigitta. It should not go under spacetelescope because it is used by Astropy too.

**Comment by zacharyburnett** [comment]
> FWIW Brigitta asked if I am interested to upstream this to Scientific Python but I was hesitant because I am scared it is going to get refactored and break stuff. But if STScI is not comfortable with this workflow in my own account, I can revisit that idea with Brigitta. It should not go under spacetelescope because it is used by Astropy too.

would it be possible to put it under OpenAstronomy?

**Comment by WilliamJamieson** [comment]
> FWIW Brigitta asked if I am interested to upstream this to Scientific Python but I was hesitant because I am scared it is going to get refactored and break stuff. But if STScI is not comfortable with this workflow in my own account, I can revisit that idea with Brigitta. It should not go under spacetelescope because it is used by Astropy too. 

We can fork and change it if it starts breaking stuff for space telescope.

**Comment by pllim** [comment]
I am not a member of OpenAstronomy

**Comment by pllim** [comment]
Let me ask around. But in the meantime, nothing stops you from using it as-is right now.

**Comment by WilliamJamieson** [comment]
> Let me ask around. But in the meantime, nothing stops you from using it as-is right now.

Its used by the rest of roman, asdf, and jdaviz... so we (STScI) have motivation to fork back if there ends up being an issue like you fear.

**Comment by pllim** [comment]
Yeah but even if I move it, the existing call would still work. So no reason to wait around for a political move here.

**Comment by pllim** [comment]
I'll probably just batch PR to all the affected repos when the move happens.

**Comment by bsipocz** [comment]
> FWIW Brigitta asked if I am interested to upstream this to Scientific Python but I was hesitant because I am scared it is going to get refactored and break stuff.

Well, just to chime in, the format is used in my repos, too, so I'm motivated enough not to break the current format :)

**Review by zacharyburnett — APPROVED** [review]

**Pull request merged**
