### PR TITLE
update labeler to v5

### PR DESCRIPTION
**Pull request by zacharyburnett**
follow-on to #1231 and #1332 

**Checklist**
- [x] ~added entry in `CHANGES.rst` under the corresponding subsection~
- [x] ~updated relevant tests~
- [x] ~updated relevant documentation~
- [x] updated relevant milestone(s)
- [x] added relevant label(s)
- [x] ~ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)~

### CODE REVIEW

**Comment by braingram** [comment]
Do you want to hold off on https://github.com/spacetelescope/romancal/pull/1332 in favor of this?

**Comment by zacharyburnett** [comment]
> Do you want to hold off on #1332 in favor of this?

That should work!

**Comment by braingram** [comment]
I opened a test PR against the source branch (which should trigger the run with the updated config and labeler v5). When you have a chance would you allow the CI to run on that PR?
https://github.com/zacharyburnett/romancal/pull/2

**Review by braingram — APPROVED** [review]
Test PR worked! Thanks for updating the config file.

**Pull request merged**
