### PR TITLE
Make test randomness deterministic

### LINKED ISSUE #769: Rampfit test intermittently failing
The fix in #725 does not quite work all of the time, on the main branch I am getting intermittent failures in the
```
romancal/ramp_fitting/tests/test_ramp_fit.py::test_one_group_small_buffer_fit_ols
```
test cases. Iterative running of this test locally (it is skipped in CI) reproduces the error locally for me. For example I get the error:
```
E           AssertionError: 
E           Not equal to tolerance rtol=1e-06, atol=0
E           
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 1.06613152e-11
E           Max relative difference: 1.06613152e-06
E            x: array(-1.000001e-05, dtype=float32)
E            y: array(-1.e-05)
```

I believe the root of this error is: https://github.com/spacetelescope/romancal/blob/2396bc7bb78e00242e705ecb588157bf1a182f2a/romancal/ramp_fitting/tests/test_ramp_fit.py#L32-L36
The intermittent failure is caused by the fact that the data/err change from run-to-run of the tests. Instead, the random number generator should be seeded so that every test is exactly reproducible among different test runs.

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Closes #769

This PR transitions all the random number generation in romancal to be both deterministic and to use the recommend numpy [Random Generator](https://numpy.org/doc/stable/reference/random/generator.html) to control random number generation. All the random number generations are seeded so the tests are entirely reproducible.

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [x] updated relevant tests
- [x] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by schlafly** [comment]
Just staring at it, looks good to me.  Are the regression tests passing?  Clearly the docs failure is a separate issue somewhere?

**Comment by WilliamJamieson** [comment]
> Just staring at it, looks good to me.  Are the regression tests passing?  Clearly the docs failure is a separate issue somewhere?

Yep it was fixed by #773.

**Comment by schlafly** [comment]
I'm happy to approve this but I need the regression test link to do so---though I can't imagine this leading to regtest issues.  Thanks!

**Comment by WilliamJamieson** [comment]
> I'm happy to approve this but I need the regression test link to do so---though I can't imagine this leading to regtest issues.  Thanks!

There is no need to run the regression tests. If you look all the changes here are only to tests which are run by the GitHub CI.

**Review by schlafly — APPROVED** [review]
LGTM.

**Pull request merged**
