### PR TITLE
RCAL-937: update s_region after running TweakRegStep.

### LINKED ISSUE #1455: Update s_region following tweakreg
I think tweakreg currently updates only the image WCS but not the s_region.  The s_region is used to determine the boundaries of the CCDs, e.g., in the MAST viewer, and we should update it when we update the WCS.

I think the WCS gets replaced here:
https://github.com/spacetelescope/romancal/blob/main/romancal/tweakreg/tweakreg_step.py#L273
but I think that's it.

Vaguely relatedly, we don't update other WCS keywords like ra/dec_ref, roll_ref.  I don't think there is a good way for us to update those in the current scheme, though, and still be able to reproduce the WCS, so I don't think we should tackle that at present.

### PR DESCRIPTION
**Pull request by mairanteodoro**
Resolves [RCAL-937](https://jira.stsci.edu/browse/RCAL-937)

Closes #1455 

This PR updates the `meta.wcsinfo.s_region` attribute after running `TweakRegStep`, which so far was only updating the WCS but not the footprint.

### Regression tests
- https://github.com/spacetelescope/RegressionTests/actions/runs/11687286223

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [X] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [X] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Review by schlafly — COMMENTED** [review]
Thanks, this looks good.  I was a little surprised that the mosaic regtests show some changes (a handful of pixels).  I think this is saying that drizzle / resample are using the s_region to compute which input pixels touch which output pixels, and maybe they don't use quite a large enough margin, so a few boundary pixels were getting slightly clipped and now are not?  I don't think we care, and resample is migrating to stcal soon, but @mcara might be able to say whether we expect the resampled images to change slightly when s_region is very slightly perturbed.

The contexts also all changed; I guess this just means that there was a CRDS context update and we need to okify everything.  Feel free to do that, thanks!

**Comment by braingram** [comment]
FWIW depending on the timing of the regtest runs I merged https://github.com/spacetelescope/stcal/pull/311 and okified those changes.

The run that produced the files for okifying was: https://github.com/spacetelescope/RegressionTests/actions/runs/11682867663
and the run I triggered afterwards showed no failures: https://github.com/spacetelescope/RegressionTests/actions/runs/11684844516

Is it possible the previous run was started after the stcal merge (~3 hrs ago) but before the okify finished which was shortly after the run fished?

I see the latest run for this PR https://github.com/spacetelescope/RegressionTests/actions/runs/11687286223 only shows `s_region` differences.

If none of this is relevant just ignore me :-P

**Comment by mcara** [comment]
> I don't think we care, and resample is migrating to stcal soon, but @mcara might be able to say whether we expect the resampled images to change slightly when s_region is very slightly perturbed.

I do not see how `s_region` can have any _direct_ effect on resample. An indirect effect can happen via a direct effect on computation of the output WCS which in turn can have an effect on resample.

One way to test this is to create a "custom" reference WCS with the old code and modify tests to use that WCS. There should not be any differences then. If you restore the code to again re-compute the output WCS (from `s_region`) and you get test failures, then it is a clear indication that test failures are due to changes in the output WCS.

**Comment by schlafly** [comment]
The current regtest run shows no pixel level data changes, consistent with Mihai's and my expectations.  I reviewed before ~4 days ago, so I don't think the stcal changes should be relevant.  But I guess as the regtests look good now I'm not inclined to try to do too much archaeology to figure out the old small thing I didn't understand.  So LGTM unless anyone else has ideas here!

**Comment by braingram** [comment]
> The current regtest run shows no pixel level data changes, consistent with Mihai's and my expectations. I reviewed before ~4 days ago, so I don't think the stcal changes should be relevant. But I guess as the regtests look good now I'm not inclined to try to do too much archaeology to figure out the old small thing I didn't understand. So LGTM unless anyone else has ideas here!

Do you think it was https://github.com/spacetelescope/stcal/pull/315

**Comment by schlafly** [comment]
Right, that's plausible!  Then it's on me for not noticing that main was also failing with the same issue.  Okay, let's go ahead.

**Comment by schlafly** [comment]
Mairan, please okify the regtests after merging, thanks!

**Comment by mairanteodoro** [comment]
Sorry I missed all the fun here while I was at a doctor's office...

The latest regtest run shows only two failures that are related to the updates to `TweakRegStep` in this PR. I believe that Brett's right, and reverting stcal PR#135 fixed the issue.

I will go ahead and merge this and then okify the regtest run listed in the description of this PR.

**Pull request merged**
