### PR TITLE
add Readthedocs badge to README

### PR DESCRIPTION
**Pull request by nden**

### CODE REVIEW

**Review by dmggh — COMMENTED** [review]
Where does that come from ? I don't see it in the build logs or in our project page on the RTD site.

**Comment by dmggh** [comment]
Does it come from the URL for our project, which is https://readthedocs.org/projects/roman-cal-pipeline/. ?

**Comment by nden** [comment]
The badge (in proper syntax for different languages is available on readthedocs project site. So yes, it comes from there.

**Comment by dmggh** [comment]
LGTM

**Review by dmggh — APPROVED** [review]

**Pull request merged**
