### PR TITLE
Rcal 239 saturation rtd

### LINKED ISSUE #340: Documentation for Saturation correction in RTD
_Issue [RCAL-239](https://jira.stsci.edu/browse/RCAL-239) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Add documentation for Roman Saturation correction to read-the-docs

### PR DESCRIPTION
**Pull request by PaulHuwe**
Closes #340 

Resolves RCAL-239

**Description**

This PR addresses updating RTD to include saturation reference files.

Checklist
- [ ] Tests

- [x ] Documentation

- [x ] Change log

- [ ] Milestone

- [ ] Label(s)

### CODE REVIEW

**Comment by PaulHuwe** [comment]
This is in draft PR until PR-218 is merged.

**Comment by PaulHuwe** [comment]
@nden @ddavis-stsci I put this into draft PR to ask you a question: when I compile these, things look okay EXCEPT for the Saturation Class Inheritance diagram. It looks like:
sat
Do you guys know how to fix it?

**Review by ddavis-stsci — APPROVED** [review]
Looks Good

**Comment by PaulHuwe** [comment]
The class diagram issue was just due to graphviz - I resolved it with a reinstall.

**Pull request merged**
