### PR TITLE
RCAL-136 Jenkins Build31 Hot Fix

### PR DESCRIPTION
**Pull request by PaulHuwe**
Resolves RCAL-136: Investigate Jenkins failure

**Description**

This PR addresses ...
- Added sorting to test parameters to preserve order for tests done by parallel pytest workers.

Checklist
- [x] Tests

- [unneeded] Documentation

- [x] Change log

- [x] Milestone

- [x] Label(s)

### CODE REVIEW

**Review by ddavis-stsci — APPROVED** [review]
LGTM

**Review by dmggh — COMMENTED** [review]
Just wondering - why didn't sorting matter earlier ?

**Comment by dmggh** [comment]
LGTM

**Comment by PaulHuwe** [comment]
Sorting wasn't needed earlier because pytest was running with just one worker. Jenkins runs pytest with multiple workers in parallel, and if they process in different orders, there is a comparison error. The way to test locally is:

pytest -n 2 

(NOTE: you need to install pytest-xdist first)

**Pull request merged**
