### PR TITLE
remove unused test code

### PR DESCRIPTION
**Pull request by braingram**
This PR removes the unused sdp-related test fixtures. Including
- `--sdp-pool` and `--standard-pool` options
- `sdp-pool` and `standard-pool` fixtures
- `SDPPoolsSource` and `BaseRomanTest` test classes
- and the commented out `raw_from_asn`

Regression tests show only unrelated error:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/652/tests

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by braingram** [comment]
nden I requested your review as these files appear to be copies of files in jwst. I think they might be in use there in [test_against_standard](https://github.com/spacetelescope/jwst/blob/77c4966a836e03f34939d3de6ba805bc0934a7d6/jwst/regtest/test_associations_standards.py#L112). That may mean that the files removed in this PR might eventually be used by romancal (or that their lack of use is a bug). Thanks and let me know if more details are helpful.

**Review by nden — APPROVED** [review]
These were copied from JWST anticipating we'll have to use them for testing generating associations but it looks like we'll have other types of associations and may not need them. I'm fine removing them. @ddavis-stsci Do you agree?

**Comment by ddavis-stsci** [comment]
Removing them is probably fine. It doesn't look like we'll have 
realistic pool files for a while.
Also if I recall they depend on the ci_watson plugin. I'm not sure how 
that will transition to
GA.

If we need them later we'll just put them back.

**Comment by braingram** [comment]
Thanks! The py39 failures are due to `roman_datamodels` dropping python 3.9 and are addressed in: https://github.com/spacetelescope/romancal/pull/1144

**Pull request merged**
