### PR TITLE
mention strun package name usage in docs

### PR DESCRIPTION
**Pull request by braingram**
Following https://github.com/spacetelescope/stpipe/pull/202 stpipe allows providing a package name to resolve ambiguous aliases provided to strun:
```
strun romancal::resample ...
```
This PR adds a note to the docs about when this might be needed.

Link to docs (note is at the end of this section): https://roman-pipeline--1476.org.readthedocs.build/en/1476/roman/pipeline_run.html#from-the-command-line

As the current stpipe required version doesn't support this I'll leave this PR as draft but request reviews for comments on the wording.

This PR makes no code changes so regression tests were not run.

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Review by schlafly — APPROVED** [review]
Thanks!

**Review by mairanteodoro — APPROVED** [review]
Looks good to me!

**Comment by braingram** [comment]
I brought this out of draft since now stpipe main has changes (https://github.com/spacetelescope/stpipe/pull/195) useful to romancal.

I updated this PR to point to stpipe main and started regtests here:
https://github.com/spacetelescope/RegressionTests/actions/runs/12169143665

**Comment by braingram** [comment]
Regtests all passed so merging.

**Pull request merged**
