### PR TITLE
Restore flux units to source catalog table

### PR DESCRIPTION
**Pull request by larrybradley**
This PR restores flux units to the source catalog table.  The units were no longer included after a recent schema change.

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Comment by larrybradley** [comment]
The failing tests are unrelated to this PR:
`AttributeError: No such attribute (sw_version) found in node`

**Comment by schlafly** [comment]
I think this issue was just related to not being based on the most recent main; merging in main seems to have resolved it.  I am  leery of adding units to the model and removing them again---I would have guessed that the data model complains when the ndarrays are replaced with quantities.  But we can revisit that in a later PR.

**Comment by larrybradley** [comment]
> I would have guessed that the data model complains when the ndarrays are replaced with quantities. But we can revisit that in a later PR.

Using the `dict` syntax avoids the validator.   In https://github.com/spacetelescope/romancal/pull/1457, the data and err array will be copies and the "removing again" step will be unnecessary.  But I need this PR to be merged first.

**Comment by schlafly** [comment]
Thanks, that makes sense.  I'm running regtests here:
https://github.com/spacetelescope/RegressionTests/actions/runs/11825383574
and will merge after those pass.

**Comment by schlafly** [comment]
All green, thanks.  https://github.com/spacetelescope/RegressionTests/actions/runs/11825383574

**Review by schlafly — APPROVED** [review]

**Pull request merged**
