### PR TITLE
Update reference pixel docs.

### PR DESCRIPTION
**Pull request by schlafly**
Resolves [RCAL-575](https://jira.stsci.edu/browse/RCAL-575)

This PR updates the documentation of the reference pixel correction to include some details about how the reference pixel correction and discretization bias interact.  In short, the reference pixel correction already corrects for the discretization bias and so no additional correction is needed.

**Checklist**
- [X] added entry in `CHANGES.rst` under the corresponding subsection
- [N/A] updated relevant tests
- [X] updated relevant documentation
- [X] updated relevant milestone(s)
- [X] added relevant label(s)

### CODE REVIEW

**Comment by schlafly** [comment]
FWIW, updated docs are here:
https://roman-pipeline--716.org.readthedocs.build/en/716/roman/refpix/description.html#discretization-bias-reference-pixel-correction
This looks fine to me and I think we can go ahead and merge.  Regression tests here:
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/228/
I suspect the failure is due to the memory allocation issue?  I do not understand it.

**Comment by ddavis-stsci** [comment]
One minor nit, the statement
"...can lead to a bias in the fluxes we derive from Roman data for stars"
is that correct? or does this affect all objects not just point sources?

I'd try and rerun the regression tests. Those errors are often transient.

**Comment by schlafly** [comment]
Thanks.  Rerunning the tests addressed this.
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/229/
I have picked your nit and replaced stars with sources.  Shall I go ahead and merge?

**Comment by ddavis-stsci** [comment]
I think it looks good, so go ahead.

**Pull request merged**
