### PR TITLE
rcal-952 Update grism flat field tests with correct input

### LINKED ISSUE #1516: Update flatfield regression test to remove xfail
_Issue [RCAL-952](https://jira.stsci.edu/browse/RCAL-952) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

update test_wfi_flat_field.py input file for grism

r0000201001001001001_0001_wfi01_uncal.asdf

to

r0000201001001001001_0001_wfi01_assignwcs.asdf

### PR DESCRIPTION
**Pull request by ddavis-stsci**
Resolves [RCAL-952](https://jira.stsci.edu/browse/RCAL-952)

Closes #1516

This PR updates the input files for the grism flatfield test and checks that the output file matches the truth file
with flat_field set to "SKIPPED"

## Tasks
- [x] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [x] update or add relevant tests
  - [x] update relevant docstrings and / or `docs/` page
  - [x] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [x] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [x] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

passing regression tests are at
https://github.com/spacetelescope/RegressionTests/actions/runs/11918027530

### CODE REVIEW

**Review by schlafly — APPROVED** [review]
LGTM, thanks!

**Comment by schlafly** [comment]
Note that I see the assert testing ref_file = N/A but I don't see the SKIPPED test explicitly; if we want this, should we add the corresponding assert?

**Comment by ddavis-stsci** [comment]
I think the test is really does the grism file process correctly up to the flat field step, so when checking with the truth file it should match all the steps, 
```
Meta Attribute  cal_step
             dq_init	COMPLETE
          saturation	COMPLETE
              refpix	COMPLETE
           linearity	COMPLETE
                dark	COMPLETE
            ramp_fit	COMPLETE
          assign_wcs	COMPLETE
          flat_field	SKIPPED
```
I guess we can add all the comparisons...

**Comment by schlafly** [comment]
Right now we check only on ref_file and it is easy for something to change in the truth files and for us to not notice it, so if we want to make sure that the step is marked as skipped I think we should explicitly check for it.  Since this is a flat field test I would not go as far as checking all preliminary steps.

**Pull request merged**
