### PR TITLE
Adding dark current to the entry points.

### PR DESCRIPTION
**Pull request by dmggh**
Adding the dark current step to the list of entry points for the unit tests that will be added.

### CODE REVIEW

**Comment by dmggh** [comment]
Update of step.py is based on my review of an earlier PR by @eslavich.

**Review by eslavich — COMMENTED** [review]
The test failure is due to this line:

```
from ..stpipe import Step
```

The name of the class in romancal is `RomanStep`.

**Review by ddavis-stsci — APPROVED** [review]
Looks good.

**Review by eslavich — APPROVED** [review]
LGTM

**Comment by dmggh** [comment]
Thanks Ed & Dave

**Pull request merged**
