### PR TITLE
RCAL-800: Set flux step status for each input

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [RCAL-800](https://jira.stsci.edu/browse/RCAL-800)

Related PRs:
- [roman_datamodel#332](https://github.com/spacetelescope/roman_datamodels/pull/332)
- [rad#395](https://github.com/spacetelescope/rad/pull/395)

This PR sets the step completion status for each input model to FluxStep.

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [x] updated relevant tests
- [x] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Review by ddavis-stsci — APPROVED** [review]
LGTM

**Review by schlafly — COMMENTED** [review]
This looks fine to me.  Do you think there are cases where we want the pipeline to continue when we have failed to flux calibrate?  My sense is that if we try to flux calibrate and fail something has gone badly wrong and we don't want to just continue and mark as skipped, but maybe I'm missing some case where that would be the desired behavior?

**Comment by schlafly** [comment]
That sounds like a good approach to me.

**Review by schlafly — APPROVED** [review]
This looks good to me.  Presumably it will break the regression tests, though, and we'll need to do an okify; are you able to do that?

**Comment by stscieisenhamer** [comment]
In principle I can and will attempt it.

**Comment by stscieisenhamer** [comment]
[Regtest #707](https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/707/)

**Comment by schlafly** [comment]
Looks good, yup, go ahead and update and okify.

**Pull request merged**
