### PR TITLE
use filename instead of meta.filename for exposure pipeline

### LINKED ISSUE #818: `ExposurePipeline` uses `meta.filename` instead of actual filename
I believe the changes in #802 are not compatible with the `test_processing_pipeline_all_saturated` regtest.

Here's a recent regtest run with this PR where only the mentioned test was run and stdout was not captured:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/311/pipeline/205/#step-206-log-97

A few relevant log lines are:
```
2023-08-08 16:45:59,578 - stpipe.ExposurePipeline - INFO - Starting Roman exposure calibration pipeline ...
2023-08-08 16:45:59,818 - stpipe.ExposurePipeline - INFO - Processing a WFI exposure <roman_datamodels.datamodels._datamodels.ScienceRawModel object at 0x7f0893db6450>
...
2023-08-08 16:51:22,126 - stpipe.ExposurePipeline - INFO - Roman exposure calibration pipeline ending...

2023-08-08 16:51:24,208 - stpipe.ExposurePipeline - INFO - Saved model in r0000101001001001001_01101_0001_WFI01_cal.asdf
```
Note the filename above does not match the output filename in the regression test:
https://github.com/spacetelescope/romancal/blob/043776069a21ee6f92f6af356293e4f4bec202bb/romancal/regtest/test_wfi_pipeline.py#L438
which causes the error
```
E                   FileNotFoundError: [Errno 2] No such file or directory: '/srv/jenkins/workspace/RT/Roman-Developers-Pull-Requests/clone/test_outputs/popen-gw1/test_processing_pipeline_all_s0/r0000101001001001001_01101_0001_WFI01_ALL_SATURATED_cal.asdf'
/srv/jenkins/workspace/RT/Roman-Developers-Pull-Requests/miniconda/envs/tmp_env0/lib/python3.11/site-packages/asdf/generic_io.py:1150: FileNotFoundError
```

This seems related to the input filename handling in exposure pipline where when provided with an `input` as a string, `input` is overwritten as a datamodel:
https://github.com/spacetelescope/romancal/blob/043776069a21ee6f92f6af356293e4f4bec202bb/romancal/pipeline/exposure_pipeline.py#L78-L85
then added to `expos_file`:
https://github.com/spacetelescope/romancal/blob/043776069a21ee6f92f6af356293e4f4bec202bb/romancal/pipeline/exposure_pipeline.py#L94-L101
before this check:
https://github.com/spacetelescope/romancal/blob/043776069a21ee6f92f6af356293e4f4bec202bb/romancal/pipeline/exposure_pipeline.py#L105-L109
which means that `meta.filename` is not overwritten here:
https://github.com/spacetelescope/romancal/blob/043776069a21ee6f92f6af356293e4f4bec202bb/romancal/pipeline/exposure_pipeline.py#L117-L118
and the `meta.filename` in the input file does not match the filename (r0000101001001001001_01101_0001_WFI01_ALL_SATURATED_uncal.asdf):
```
In [10]: af['roman']['meta']['filename']
Out[10]: 'r0000101001001001001_01101_0001_WFI01_uncal.asdf'
```
making the output filename incorrect.

### PR DESCRIPTION
**Pull request by braingram**
Closes #818

Use actual filename instead of `meta.filename` for `ExposurePipeline` to match behavior prior to #802 

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by braingram** [comment]
Regression test shows 1 unrelated failure:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/334/tests

The failure appears to be the one that only occurs intermittently during runs with xdist.
```
TypeError: buffer is too small for requested array
Stacktrace
rtdata = {'input': '/srv/jenkins/workspace/RT/Roman-Developers-Pull-Requests/clone/test_outputs/popen-gw4/test_ramp_fitting_ste...ut': None,
 'remote_results_path': None,
 'test_name': None,
 'traceback': None,
 'truth': None,
 'truth_remote': None}
ignore_asdf_paths = {'ignore': ['meta.[date, filename]', 'asdf_library', 'history', 'cal_logs']}
    @pytest.mark.bigdata
    def test_ramp_fitting_step(rtdata, ignore_asdf_paths):
        """Testing the ramp fitting step"""
        input_data = "r0000101001001001001_01101_0001_WFI01_jump.asdf"
        rtdata.get_data(f"WFI/image/{input_data}")
        rtdata.input = input_data
    
        args = [
            "romancal.step.RampFitStep",
            rtdata.input,
            "--save_opt=True",
            "--opt_name=rampfit_opt.asdf",
        ]
>       RomanStep.from_cmdline(args)
```

**Review by ddavis-stsci — CHANGES_REQUESTED** [review]
The error that you are seeing is being worked in another ticket and should be done soon. 

This will also break processing the files in an association so I'm not sure this is a good idea.

**Comment by braingram** [comment]
Thanks for taking a look.

Is there a unit or regtest that tests loading association files? If not, is there a file you are using for testing that you would share?

I attempted to make these changes in a way that preserved the association loading. In what way is it broken? Is there an error you are seeing locally and if so would you share the details?

**Comment by ddavis-stsci** [comment]
It should work with just
strun  roman_elp r90001-a3001_image_001_asn.json

This worked on July 28 but I'm now seeing the same error as you.
I'll add a ticket for this and try to look at it this sprint since we'll 
need this for
resample and outlier detection in the pipeline.

**Comment by braingram** [comment]
> It should work with just strun  roman_elp r90001-a3001_image_001_asn.json This worked on July 28 but I'm now seeing the same error as you. I'll add a ticket for this and try to look at it this sprint since we'll need this for resample and outlier detection in the pipeline.

Thanks for the reply.

I had already started writing an issue for roman_datamodels describing some issues with association file opening before I saw your reply: https://github.com/spacetelescope/roman_datamodels/issues/267 Feel free to reference it in the ticket. My attempts at easy fixes did not result in getting it working so I can't open a PR to fix it at this point.

Given that this PR addresses more that just association file inputs (the prior regression test failure was with a single asdf file as input) do you think it's worth fixing the handling of non-association inputs (since association processing is broken)?

**Comment by ddavis-stsci** [comment]
My inclination is to wait and fix these as a unit. Another point is that 
this code is a "quick" fix and will be updated
once rcal-620, "Update ModelContainer for use with Context manager", is 
done.
This should allow a more robust solution to the problem. Mairan was 
working on the model container so I'll
check and see if this is scheduled.

**Comment by braingram** [comment]
Closing this as stale.

**Pull request closed without merging**
