### PR TITLE
Documentation of readnoise reference files (RCAL-141)

### PR DESCRIPTION
**Pull request by dmggh**
Closes #

Resolves RCAL-141

**Description**
Romancal readnoise reference file docs 

This PR addresses ...

Checklist
- [ ] Tests

- [X ] Documentation

- [ ] Change log

- [ ] Milestone

- [ ] Label(s)

### CODE REVIEW

**Comment by nden** [comment]
@dmggh There are three PRs opened for the same ticket. Can any of them be closed?  Which one should be reviewed?

**Comment by dmggh** [comment]
@nden : my  3 PRs for this JIRA ticket are #234, #248, and #250. The first 2 of these can be closed. #250 was my most recent attempt, but failed due to dark current CI unit tests failing. PR #251 was opened by @ddavis-stsci as a draft; perhaps he can weigh in on which of #250 or #251 should be reviewed.

**Comment by dmggh** [comment]
#251 has been closed, so #250 (this PR) should be reviewed

**Comment by dmggh** [comment]
Closing as this PR is superseded  by PR #256

**Pull request closed without merging**
