### PR TITLE
Use dark slope in ramp fitting

### PR DESCRIPTION
**Pull request by schlafly**
Presently the ramp fitting step operates on dark-subtracted ramps, but assumes that the Poisson noise in those ramps can be well estimated by the square root of the rate.  The dark current contribution to the rate should be part of that Poisson noise, but is omitted because the step operates on dark-subtracted ramps.

This PR adds the dark current portion of the dark reference file (dark_slope) back into the ramp, performs the ramp fitting, and then removes the contribution from the slopes.  This is related to
https://innerspace.stsci.edu/display/RI/Ramp+Fitting+-+v1
.  It has the slight benefit of being more correct (we're choosing weights better), but being more convoluted (we're adding and subtracting dark current.

We'll also use more memory than previously---the darks are rather big, and now we need to have them in memory during ramp fitting, which is when we have peak memory usage.

This changes the variances slightly and is expected to break regression tests.

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [X] updated relevant tests
- [X] updated relevant documentation
- [ ] updated relevant milestone(s)
- [X] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by schlafly** [comment]
@tddesjardins , do you want to review this use of dark_slope during ramp fitting?  This isn't quite what was requested in https://innerspace.stsci.edu/display/RI/Ramp+Fitting+-+v1 (which would require a API change to stcal), but I think it's in some way more correct.

**Comment by schlafly** [comment]
@t-brandt, this is the PR with the dark_slope implementation we talked about; I'd love to get this "blessed" by RTB so that I can merge.

**Comment by tddesjardins** [comment]
LGTM; RTB approves!

**Review by ddavis-stsci — APPROVED** [review]
The code look fine to me.

**Pull request merged**
