### PR TITLE
Changes and improvements to the RomanCal documentation/user manual.

### PR DESCRIPTION
**Pull request by mairanteodoro**
Resolves [RCAL-409](https://jira.stsci.edu/browse/RCAL-409)

This draft PR will address all the changes to the RomanCal documentation/user manual.

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [X] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by mairanteodoro** [comment]
This is what the page layout looks like with the changes in this first commit:

Screen Shot 2022-10-27 at 12 18 39 PM

**Comment by schlafly** [comment]
That looks much better!  We could look ourselves if the warning about package_index.rst missing a reference were resolved; right now the docs aren't building.

You did the same thing I did with the romanisim docs and moved from stsci-rtd-theme to sphinx-rtd-theme.  We should probably have a wider discussion about stsci-rtd-theme; if we're not using it, it's a bad sign.  

This will probably come in at the text edit stage, but we should also think about the right ordering of the sections.  I think the current ordering is more organic growth than a conscious decision about what should be first vs. last.

Anyway, looks good to me to merge following resolution of the doc build issue.

**Comment by nden** [comment]
Needs a change log

**Review by schlafly — APPROVED** [review]

**Review by nden — APPROVED** [review]
Needs a change log

**Comment by mairanteodoro** [comment]
> Needs a change log

Done.

**Pull request merged**
