### PR TITLE
Replace create_s_region with stcal's compute_s_region_keyword.

### LINKED ISSUE #1466: create_s_region, add_s_region, and create_footprint duplicate stcal functions
The `create_s_region` function duplicates the functionality of stcal's `compute_s_region_keyword` https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stcal/alignment/util.py#L710 and should be replaced with the stcal version.

The `create_footprint` and `add_s_region` functions together duplicate the behavior of stcal's `compute_s_region_imaging` https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stcal/alignment/util.py#L639 and a small stcal refactor that splits `compute_s_region_imaging` in two could cover the direct use of `create_footprint` in Romancal resample without affecting the way `compute_s_region_imaging` is currently used in jwst.

Discovered while investigating https://github.com/spacetelescope/romancal/issues/1455

### PR DESCRIPTION
**Pull request by mairanteodoro**
Resolves [RCAL-948](https://jira.stsci.edu/browse/RCAL-948)

Partially resolves #1466

This PR updates `romancal` to reduce duplicate code by using `stcal`'s `compute_s_region_keyword()`.

### Regression test
- https://github.com/spacetelescope/RegressionTests/actions/runs/11693055226

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `24Q4_B15` (use the [latest build](https://github.com/spacetelescope/romancal/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [X] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [x] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/romancal/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

  - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
  - ``changes/<PR#>.docs.rst``
  - ``changes/<PR#>.stpipe.rst``
  - ``changes/<PR#>.associations.rst``
  - ``changes/<PR#>.scripts.rst``
  - ``changes/<PR#>.mosaic_pipeline.rst``
  - ``changes/<PR#>.patch_match.rst``

  ## steps
  - ``changes/<PR#>.dq_init.rst``
  - ``changes/<PR#>.saturation.rst``
  - ``changes/<PR#>.refpix.rst``
  - ``changes/<PR#>.linearity.rst``
  - ``changes/<PR#>.dark_current.rst``
  - ``changes/<PR#>.jump_detection.rst``
  - ``changes/<PR#>.ramp_fitting.rst``
  - ``changes/<PR#>.assign_wcs.rst``
  - ``changes/<PR#>.flatfield.rst``
  - ``changes/<PR#>.photom.rst``
  - ``changes/<PR#>.flux.rst``
  - ``changes/<PR#>.source_detection.rst``
  - ``changes/<PR#>.tweakreg.rst``
  - ``changes/<PR#>.skymatch.rst``
  - ``changes/<PR#>.outlier_detection.rst``
  - ``changes/<PR#>.resample.rst``
  - ``changes/<PR#>.source_catalog.rst``
</details>

### CODE REVIEW

**Comment by mairanteodoro** [comment]
Tagging @emolter since I can't find him on the list of reviewers.

**Review by emolter — APPROVED** [review]
LGTM

**Comment by schlafly** [comment]
Judging by the regtest changes, it looks like stcal's variant uses less precision.  It looks like this is still ~3 uas, so I have trouble imagining we care about this accuracy for s_region.  But is it known or expected that we changed the precision here?

**Comment by schlafly** [comment]
Thanks, okay.  Then I'll treat this as expected and reasonable and approve, thanks!

**Review by schlafly — APPROVED** [review]

**Pull request merged**
