### PR TITLE
[SCSB-169] add user input to specify `CRDS_CONTEXT`

### PR DESCRIPTION
**Pull request by zacharyburnett**
Resolves [SCSB-169](https://jira.stsci.edu/browse/SCSB-169)

[image](https://github.com/zacharyburnett/romancal/actions/workflows/roman_ci.yml)

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [x] updated relevant milestone(s)
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by zacharyburnett** [comment]
tested with 
- https://github.com/zacharyburnett/romancal/actions/runs/10354836088
- https://github.com/zacharyburnett/romancal/actions/runs/10354837285

**Comment by ddavis-stsci** [comment]
Is the default still the current operational context? 
So if I leave this blank it will automatically pick up the latest context?
If we are adding the context to the checks should we also add the server so we can test changes before updates go public?

**Comment by zacharyburnett** [comment]
> Is the default still the current operational context? So if I leave this blank it will automatically pick up the latest context? 

Yes and yes

> If we are adding the context to the checks should we also add the server so we can test changes before updates go public?

Good idea!

**Review by ddavis-stsci — APPROVED** [review]
LGTM

**Comment by braingram** [comment]
Oops. Shouldn't the defaults be `roman-crds` instead of `jwst-crds`? It's causing CI failures:
```
ERROR romancal/ramp_fitting/tests/test_ramp_fit_cas22.py::test_fits[extranoise-jump-var_rnoise] - crds.core.exceptions.CrdsConfigError: CRDS server at 'https://jwst-crds.stsci.edu/' is inconsistent with observatory 'roman'. You may be configured for the wrong project.  Check CRDS_SERVER_URL and CRDS_OBSERVATORY environment settings.  See https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/ (JWST) or https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ (HST) for information on configuring CRDS.
```

**Comment by zacharyburnett** [comment]
> Oops. Shouldn't the defaults be `roman-crds` instead of `jwst-crds`? It's causing CI failures:
> 
> ```
> ERROR romancal/ramp_fitting/tests/test_ramp_fit_cas22.py::test_fits[extranoise-jump-var_rnoise] - crds.core.exceptions.CrdsConfigError: CRDS server at 'https://jwst-crds.stsci.edu/' is inconsistent with observatory 'roman'. You may be configured for the wrong project.  Check CRDS_SERVER_URL and CRDS_OBSERVATORY environment settings.  See https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/ (JWST) or https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ (HST) for information on configuring CRDS.
> ```

yeah sorry about that! I fixed it with a hotfix. An issue with working with two identical PRs at the same time 😅

**Pull request merged**
