### PR TITLE
Rcal-83 Update optical element ENG -> F213

### PR DESCRIPTION
**Pull request by ddavis-stsci**
The engineering filter is to be officially removed from the set of elements and replaced with F213.

### CODE REVIEW

**Comment by eslavich** [comment]
We'll need to update the CRDS validations as well, I'll create a CCD ticket

**Review by PaulHuwe — APPROVED** [review]

**Review by dmggh — APPROVED** [review]

**Comment by eslavich** [comment]
@nden since this has been merged, should we make the update in crds before build 0.1 as well?

**Comment by ddavis-stsci** [comment]
Ughh! I forgot about CRDS, and was trying to get it in before the code freeze at the end of the week.I think I can back that out if it is a problem.

**Comment by eslavich** [comment]
We updated the value in crds and the change will be included in the release we make for romancal, so this shouldn't be a problem.

**Comment by nden** [comment]
Thanks Ed!

**Comment by ddavis-stsci** [comment]
That's great! Thanks.

**Pull request merged**
