### PR TITLE
delete unreachable code

### PR DESCRIPTION
**Pull request by braingram**
As noted https://github.com/spacetelescope/romancal/commit/c49de361201c37ee2149e9e537645137bd6df655#r144502886

https://github.com/spacetelescope/romancal/pull/1241 included unreachable code.

This is being flagged by sonarqube and preventing regression tests.

This PR deletes the unreachable code. I can also confirm that I intended to delete the code for #1241 but missed it in the swatch of changes.

Regression tests running:
https://github.com/spacetelescope/RegressionTests/actions/runs/10043812086
passed quality gate, tests running.

Fixes: https://github.com/spacetelescope/romancal/issues/1321

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by zacharyburnett** [comment]
whoops sorry, jumped the gun and made a duplicate PR 😅

**Review by schlafly — APPROVED** [review]
Feel free to merge when you're ready; clearly orphaned code.

Out of curiosity, the orphaned code looks to play the buffering game; is that a feature that we still have elsewhere?  Thanks!

**Comment by braingram** [comment]
> Feel free to merge when you're ready; clearly orphaned code.
> 
> Out of curiosity, the orphaned code looks to play the buffering game; is that a feature that we still have elsewhere? Thanks!

Thanks! The orphaned code is all pertaining to the `get_sections` API of `ModelContainer`. This didn't quite work as intended (it didn't prevent loading all models into memory and in the worst case would read each model fresh from disk for every ~1 MB of input data).

The `ModelLibrary` does not have `get_sections` and instead the code now computes the median of the already in-memory models. Outlier detection will continue to be a bottleneck for large associations until the median algorithm can be reworked. I'm happy to provide more details if they're helpful.

**Comment by braingram** [comment]
Regression tests show only the expected minor differences from #1241

**Pull request merged**
