### PR TITLE
Remove link to non-existent STScI logo

### PR DESCRIPTION
**Pull request by larrybradley**
The `stsci_logo.png` does not exist in `docs/_static`.  It looks like this line was copied from the`jwst` readme, but the logo was not.

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by larrybradley** [comment]
I don't have permissions to add labels or milestones.  @nden

**Comment by schlafly** [comment]
Looks good to me.  A related option would be to change it to the Roman logo, which we do have in docs/_static.
roman_logo_black_w200px.png

**Comment by nden** [comment]
@larrybradley permissions fixed

**Comment by larrybradley** [comment]
@schlafly The Roman logos in `docs/_static` both have transparent backgrounds and are black or white.  The black logo will be invisible for users using GitHub dark mode and vice versa for the white logo with light mode.

**Review by schlafly — APPROVED** [review]

**Pull request merged**
