### PR TITLE
Adding DarkModel & Schema

### PR DESCRIPTION
**Pull request by PaulHuwe**
Initial implementation of the DataModel and schema for dark current files.

### CODE REVIEW

**Comment by nden** [comment]
This looks good for now but let's wait until Thu and see if we get additional directions on the file structure.

One thing I want to point out is that in the future we may want to exclude the `core` schema from the `reference_file` schema. The reason is that `core` will grow and represent a science file, including many attributes not needed by reference files. This change can wait though until there' s more clarity about the data.

**Review by eslavich — APPROVED** [review]
This looks good and seems to match the sample dark reference that Tyler sent me today.

**Comment by PaulHuwe** [comment]
He added one thing that I want to double check before merging this.

**Comment by PaulHuwe** [comment]
Checked for now. As we iterate on this, may tweak it further.

**Pull request merged**
