### PR TITLE
RCAL-805: Split cal_step into L2 & L3

### LINKED ISSUE #1163: Split cal_step into L2 & L3 in Datamodels
_Issue [RCAL-804](https://jira.stsci.edu/browse/RCAL-804) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Split cal_step into Level 2 and Level 3 versions. Remove resample from L2 and remove everything but outlier_detection, skymatch, and resample from L3.

### PR DESCRIPTION
**Pull request by PaulHuwe**
Resolves [RCAL-805](https://jira.stsci.edu/browse/RCAL-805)

Closes #1163 #1164 

This PR addresses changes the split of cal_step into level 2 and level 3 versions. NOTE: these changes require updates to romancal regression test files as shown in: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/692/

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by schlafly** [comment]
This looks good to me.

**Review by mairanteodoro — COMMENTED** [review]
Looks good to me. Thanks, @PaulHuwe!

**Comment by PaulHuwe** [comment]
> This looks good to me.

Could you approve it so I can merge it?

**Review by ddavis-stsci — APPROVED** [review]
LGTM

**Pull request merged**
